<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use DB;

class KategoriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create('id_ID');
        $kategori = [
            [
        		"nama" => 'dapur',
        		"slug" => "dapur",
        		"description" => "alat kebutuhan dapur",
        		"status" => 1,
                "popular" => 1,
                "image" => "dapur.jpg",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "elektronik dapur, aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
        	[
        		"nama" => 'elektronik',
        		"slug" => "elektronik",
        		"description" => "macam macam alat elektronik",
        		"status" => 1,
                "popular" => 1,
                "image" => "elektronik.jpg",
                "meta_title" => "elektronik",
                "meta_descrip" => "kebutuhan elektronik, alat kelistrikan, kabel, media",
                "meta_keyword" => "media player, vaporizer, alat elektronik, elektronik dapur,handphone,komputer,laptop,tablet,kamera ",
        	],
        	[
        		"nama" => 'fashion',
        		"slug" => "fashion",
        		"description" => "macam macam kebutuhan fashion",
        		"status" => 1,
                "popular" => 1,
                "image" => "fashion.jpg",
                "meta_title" => "fashion",
                "meta_descrip" => "kebutuhan fashion,pakaian,baju,celana",
                "meta_keyword" => "aksesoris,baju,pakaian,celana,pakaian dalam,bra",
            ],
            [
        		"nama" => 'buku',
        		"slug" => "buku",
        		"description" => "macam macam kebutuhan buku untuk belajar dan hiburan",
        		"status" => 1,
                "popular" => 0,
                "image" => "buku.jpg",
                "meta_title" => "buku",
                "meta_descrip" => "kebutuhan baca buku,buku belajar,buku hiburan,kitab",
                "meta_keyword" => "kitab,buku,kertas,hiburan,hobi,novel,komik,pendidikan",
        	],
            [
        		"nama" => 'dekorasi',
        		"slug" => "dekorasi",
        		"description" => "macam macam alat hias",
        		"status" => 1,
                "popular" => 1,
                "image" => "dekorasi.jpg",
                "meta_title" => "dekorasi",
                "meta_descrip" => "kebutuhan hias,alat hias,hiasan rumah,dekorasi dinding,dekorasi taman,dekorasi kamar",
                "meta_keyword" => "dekorasi,hiasan,wallpaper,action figure,patung,cat,sticker",
        	],
            [
        		"nama" => 'hobi',
        		"slug" => "hobi",
        		"description" => "alat kebutuhan hobi",
        		"status" => 1,
                "popular" => 1,
                "image" => "hobi.jpg",
                "meta_title" => "hobi",
                "meta_descrip" => "kebutuhan hobi,alat hobi,macam alat hobi",
                "meta_keyword" => "hobi,komputer,bola,raket,sepatu,alat musik,figure,olahraga,boneka,kartu",
        	],
            [
        		"nama" => 'gaming',
        		"slug" => "gaming",
        		"description" => "alat kebutuhan gaming",
        		"status" => 1,
                "popular" => 1,
                "image" => "gaming.jpg",
                "meta_title" => "gaming",
                "meta_descrip" => "macam alat gaming, kebutuhan gaming,controller,playstation,komputer",
                "meta_keyword" => "game,gaming,controller,playstation,xbox,nintendo,kaset game,console,aksesoris game",
        	],
            [
        		"nama" => 'handphone',
        		"slug" => "handphone",
        		"description" => "macam macam alat komunikasi",
        		"status" => 1,
                "popular" => 1,
                "image" => "handphone.jpg",
                "meta_title" => "handphone",
                "meta_descrip" => "berbagai macam handphone,alat komunikasi",
                "meta_keyword" => "handphone,case,casing,charger,xiaomi,realme,nokia,iphone,samsung,huawei,kamera,tablet,aksesoris handphone,hp",
        	],
            [
        		"nama" => 'kecantikan',
        		"slug" => "kecantikan",
        		"description" => "macam macam obat dan alat kecantikan",
        		"status" => 1,
                "popular" => 1,
                "image" => "kecantikan.jpg",
                "meta_title" => "kecantikan",
                "meta_descrip" => "macam macam alat kecantikan,make up, skincare",
                "meta_keyword" => "kecantikan,make up,skincare,vitamin,aksesoris,hobi",
        	],
            [
        		"nama" => 'kesehatan',
        		"slug" => "kesehatan",
        		"description" => "macam macam obat dan alat kesehatan",
        		"status" => 1,
                "popular" => 1,
                "image" => "kesehatan.jpg",
                "meta_title" => "kesehatan",
                "meta_descrip" => "kebutuhan kesehatan,alat kesehatan,obat obatan",
                "meta_keyword" => "obat,kesehatan,alat medis",
        	],
            [
        		"nama" => 'komputer dan laptop',
        		"slug" => "komputer",
        		"description" => "macam macam komputer dan laptop",
        		"status" => 1,
                "popular" => 1,
                "image" => "komputer dan laptop.jpg",
                "meta_title" => "komputer dan laptop",
                "meta_descrip" => "macam macam alat komputer dan laptop",
                "meta_keyword" => "komputer,laptop,ram,ssd,hardisk,intel,amd,keyboard,monitor,mouse,software",
        	],
            [
        		"nama" => 'logam mulia',
        		"slug" => "logam-mulia",
        		"description" => "macam macam logam mulia",
        		"status" => 1,
                "popular" => 0,
                "image" => "logam mulia.jpg",
                "meta_title" => "logam mulia",
                "meta_descrip" => "macam macam logam mulia, perhiasan logam mulia",
                "meta_keyword" => "logam mulia,emas,ruby,silver,tiara,berlian,perhiasan,investasi",
        	],
            [
        		"nama" => 'makanan dan minuman', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'alat tulis kantor', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'olahraga', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'otomotif', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'perawatan hewan', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'perawatan tubuh', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'perlengkapan pesta', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'pertukangan', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'rumah tangga', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'tour travel', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
            [
        		"nama" => 'wedding', 
        		"slug" => 22,
        		"description" => "Depok",
        		"status" => 1,
                "popular" => 2,
                "image" => "1",
                "meta_title" => "dapur",
                "meta_descrip" => "kebutuhan dapur,alat dapur,memasak",
                "meta_keyword" => "aksesoris dapur, peralatan dapur, penyimpan makanan",
        	],
        ];
        foreach ($kategori as $key => $value) {
            DB::table('kategori')->insert([
                'nama' => $value['nama'],
                'slug' => $value['slug'],
                'description' => $value['description'],
                'status' => $value['status'],
                'image' => $value['image'],
                'meta_title' => $value['meta_title'],
                'meta_descrip' => $value['meta_descrip'],
                'meta_keyword' => $value['meta_keyword'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        }
    }
}
