<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use DB;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = [
            //DAPUR
          [
            "cate_id" => '1',
            "nama" => "Pisau Buah",
            "slug" => "Pisau-Buah",
            "small_description" => "Pisau Stainless Steel",
            "description" => "Pisau Stainless Steel yang Anti Karat dan Tajam",
            "original_price" => 8000,
            "selling_price" => 10000,
            "image" => "pisau buah.jpg",
            "qty" => 14,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "pisau buah",
            "meta_keyword" => "pisau,buah,stainless steel,stainless,steel",
            "meta_description" => "macam-macam pisau,pisau tajam,pisau stainless steel",
            ],
            [
            "cate_id" => '1',
            "nama" => "Kompor Rinnai",
            "slug" => "Kompor-Rinnai",
            "small_description" => "Rinnai Kompor Gas 2 Tungku",
            "description" => "RI302S dikenal api super hemat karena pemakaian gas lebih hemat 20% daripada yang lain. ",
            "original_price" => 315000,
            "selling_price" => 285000,
            "image" => "kompor rinnai.jpg",
            "qty" => 9,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "kompor rinnai",
            "meta_keyword" => "kompor, kompor gas, rinnai, stainless steel",
            "meta_description" => "macam macam kompor merek rinnai",
            ],


          //ELEKTRONIK
            [
            "cate_id" => '2',
            "nama" => "Philips Air Purifier 1000",
            "slug" => "Philips-Air-Purifier-1000",
            "small_description" => "Philips Air Purifier, 1000 Series, NanoProtect HEPA S3 filter",
            "description" => "Pemurnian unggul yang bisa digunakan di ruangan dengan luas maksimal 63 m2 Vitashield IPS dengan desain aerodinamis dan Filter NanoProtect Pro memiliki laju pemberian udara bersih yang ditingkatkan hingga 270 m3/jam. Sistem ini dapat menghilangkan partikel ultra-kecil hingga 0,02um secara efektif Selain itu, sistem ini menyaring gas berbahaya seperti formaldehida dan TVOC.",
            "original_price" => 3500000,
            "selling_price" => 2189000,
            "image" => "philips air purifer.jpg",
            "qty" => 7,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Philips Air Purifier 1000",
            "meta_keyword" => "philips, air purifier, purifier, pendingin ruangan",
            "meta_description" => "macam macam alat elektronik pendingin ruangan",
            ],
            [
            "cate_id" => '2',
            "nama" => "Toshiba LED TV",
            "slug" => "Toshiba-LED-TV",
            "small_description" => "HD Smart Android 32inch - 32V35KP ",
            "description" => "Blockbuster performance guaranteed. Hadirkan bioskop di rumah. FILMMAKER MODE dan HDR menghadirkan pengalaman menonton lebih imersif. Hubungkan dengan platform streaming favorit Anda untuk mengakses konten yang disukai.",
            "original_price" => 10403000,
            "selling_price" => 9800000,
            "image" => "Toshiba LED TV.jpg",
            "qty" => 17,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "Toshiba LED TV",
            "meta_keyword" => "TV, Thosiba, TV thosiba, TV Box",
            "meta_description" => "macam-macam TV merek Toshiba",
            ],


          //FASHION
            [
            "cate_id" => '3',
            "nama" => "Mukena Zianisa Border",
            "slug" => "Mukena-Zianisa-Border",
            "small_description" => "Mukena Zianisa Border Hadiza Series Allsize - Blue",
            "description" => "Dengan ukuran plus size dan bahan teradem yang membuat Bunda lebih khusyuk ketika beribadah, Padupadan warna yang cantik serta tekstur kainnya yang lembut dan dingin membuat bunda nyaman dalam beribadah",
            "original_price" => 269000,
            "selling_price" => 144000,
            "image" => "Mukena Zianisa Border.jpg",
            "qty" => 21,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Mukena Zianisa Border",
            "meta_keyword" => "mukena, alat sholat",
            "meta_description" => "macam-macam mukena untuk sholat",
            ],
            [
            "cate_id" => '3',
            "nama" => "Hodie Sweater",
            "slug" => "Hodie-Sweater",
            "small_description" => "HOODIE POLOS WANITA/SWEATER POLOS PRIA JAKET",
            "description" => "Hoodie bahan katun FLECEE Bahannya lembut Bahan adem, Nyaman dipakai, jahitan rapi, tidak mudah luntur ",
            "original_price" => 58000,
            "selling_price" => 67500,
            "image" => "Hodie Sweater.jpg",
            "qty" => 32,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "Hodie Sweater",
            "meta_keyword" => "hodie, hodie polos, sweater, jaket, jaket wanita, jaket pria",
            "meta_description" => "macam-macam hodie dan sweater",
            ],


          //BUKU
            [
            "cate_id" => '4',
            "nama" => "Buku The Intelligent Investor ",
            "slug" => "Buku-The-Intelligent-Investor ",
            "small_description" => "Buku The Intelligent Investor (Edisi Revisi) . Benjamin Graham HC",
            "description" => "Buku ini menggambarkan dengan sangat brilian kerangka emosional dan alat-alat analisis penting penentu sukses finansial seorang investor. ",
            "original_price" => 195000,
            "selling_price" => 165700,
            "image" => "Buku The Intelligent Investor.jpg",
            "qty" => 4,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "",
            "meta_keyword" => "",
            "meta_description" => "",
            ],
            [
            "cate_id" => '4',
            "nama" => "Detektif Conan VS Men Of The Black Organization",
            "slug" => "Detektif-Conan-VS-Men-Of-The-Black-Organization",
            "small_description" => "Detektif Conan VS Men Of The Black Organization vol.2",
            "description" => "Penyusunan kembali mata-mata CIA, Rena Mizunashi, ke organisasi hitam berhasil walau harus ditukar dengan kematian agen penyelidik FBI, Shuichi Akai!",
            "original_price" => 53000,
            "selling_price" => 45000,
            "image" => "Detektif Conan.jpg",
            "qty" => 25,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Detektif Conan",
            "meta_keyword" => "kartun, detektif conan",
            "meta_description" => "macam-macam buku komik dan kartun",
            ],


          //DEKORASI
            [
            "cate_id" => '5',
            "nama" => "Luxury Wall Decoration 3D",
            "slug" => "Luxury-Wall-Decoration-3D",
            "small_description" => "Luxury Wall Decoration 3D / Hiasan Dinding Daun Ginkgo Emas - A",
            "description" => "Material : Luxury Metal Iron Gold Size : 110cm x 55cm",
            "original_price" => 1600000,
            "selling_price" => 1452000,
            "image" => "Luxury Wall.jpg",
            "qty" => 9,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Luxury Wall Decoration 3D",
            "meta_keyword" => "dekorasi, hiasan, dekorasi tembok, hiasan dinding",
            "meta_description" => "macam macam dekorasi tembok rumah",
            ],
            [
            "cate_id" => '5',
            "nama" => "Rak Dinding Besi Dekorasi",
            "slug" => "Rak-Dinding-Besi-Dekorasi",
            "small_description" => "Rak Dinding Besi Dekorasi Bentuk Hexagonal Minimalis Modern Vintage",
            "description" => "memiliki fitur unggulan yaitu : 3 Titik Ambalan Utama, 2 Lubang Paku permanen, Cat Anti Karat, Pengaman Ambalan 10 Titik, Besi SNI Kualitas Tinggi",
            "original_price" => 80000,
            "selling_price" => 59999,
            "image" => "Rak Dinding Besi.jpg",
            "qty" => 6,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "Rak Dinding Besi Dekorasi",
            "meta_keyword" => "dekorasi, rak, rak dinding, hiasan, dekorasi tembok, hiasan dinding",
            "meta_description" => "macam macam dekorasi tembok atau dinding rumah",
            ],


          //HOBI
            [
            "cate_id" => '6',
            "nama" => "Gitar Akustik Mandalika",
            "slug" => "Gitar-Akustik-Mandalika",
            "small_description" => "Gitar akustik Mandalika DL-02 Original",
            "description" => "Gitar Akustik Mandalika Premium Brand Original From Indonesia, Body Jumbo NEXCt Cutaway, suara yang dihasilkan beda banget dari Gitar sekelasnya, barang buatan INDONESIA with wooden pickguard",
            "original_price" => 550000,
            "selling_price" => 450000,
            "image" => "Gitar Akustik.jpg",
            "qty" => 21,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Gitar Akustik",
            "meta_keyword" => "Gitar, Akustik, Musik, Alat music",
            "meta_description" => "Kebutuhan hobi alat musik",
            ],
            [
            "cate_id" => '6',
            "nama" => "Gundam Transformers",
            "slug" => "Gundam-Transformers",
            "small_description" => "Gundam Transformers HGBD R09 SELTSAM 58305",
            "description" => "A deformed aircraft with special armaments such as a huge telescopic right arm, a large lance, and a shield launcher with a barrel",
            "original_price" => 288000,
            "selling_price" => 259000,
            "image" => "Gundam Transformers.jpg",
            "qty" => 8,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "Gundam Transformers",
            "meta_keyword" => "gundam, transformers, rakit gundam",
            "meta_description" => "macam-macam mainan gundam",
            ],


          //GAMING
            [
            "cate_id" => '7',
            "nama" => "Mouse Gaming AULA S20",
            "slug" => "Mouse-Gaming-AULA-S20",
            "small_description" => "Mouse Gaming AULA S20 2400DPI RGB Driver Macro Software",
            "description" => "Bahan mirip kulit Rol karet Empat gigi DPI Tombol samping LOGO glow Plating flank Pergantian cepat dan sensitif",
            "original_price" => 110000,
            "selling_price" => 72500,
            "image" => "Mouse Gaming.jpg",
            "qty" => 44,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Mouse Gaming AULA S20",
            "meta_keyword" => "mouse, gaming, mouse gaming",
            "meta_description" => "macam-macam perlengkapan gaming",
            ],
            [
            "cate_id" => '7',
            "nama" => "Keybord Mouse Converter Controller Set",
            "slug" => "Keybord-Mouse-Converter-Controller-Set",
            "small_description" => "Game HP Mobile Phone Gaming Keybord Mouse Converter Controller Set",
            "description" => "PUBG Call of Duty Mobile Controller with Keyboard and Mouse.",
            "original_price" => 700000,
            "selling_price" => 650000,
            "image" => "Converter Mobile.jpg",
            "qty" => 4,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "Keybord Mouse Converter Controller Set",
            "meta_keyword" => "Gaming mobile, converter mobile, converter keybord, converter mouse",
            "meta_description" => "macam-macam perlengkapan gaming",
            ],


          //HANDPHONE
            [
            "cate_id" => '8',
            "nama" => "XIAOMI 12 PRO 12/256",
            "slug" => "XIAOMI-2-PRO-12/256",
            "small_description" => "Xiaomi 12 Pro 12/256 Blue",
            "description" => "XIAOMI 12 PRO RAM 12GB ROM 256GB GARANSI RESMI 15 BULAN XIAOMI INDONESIA",
            "original_price" => 13100000,
            "selling_price" => 12999999,
            "image" => "Xioami.jpg",
            "qty" => 20,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "Xiaomi 12 Pro 12/256 Blue",
            "meta_keyword" => "Xioami, smartphone, xioami 12 pro, handphone",
            "meta_description" => "macam-macam handphone berbagai merek",
            ],
            [
            "cate_id" => '8',
            "nama" => "Samsung Galay Z Fold 3 5G",
            "slug" => "Samsung-Galay-Z-Fold-3-5G",
            "small_description" => "Samsung Galay Z Fold 3 5G 16/512GB",
            "description" => "Samsung Galay Z Fold 3 5G 16/512GB 256GB Fold3 Garansi Resmi SEIN - 256GB INTER, Silver",
            "original_price" => 19450000,
            "selling_price" => 19350000,
            "image" => "Samsung.jpg",
            "qty" => 23,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Samsung Galay Z Fold 3 5G",
            "meta_keyword" => "samsung, smartphone, z fold, handphone",
            "meta_description" => "macam-macam smartphone berbagai merek",
            ],



          //KECANTIKAN
            [
            "cate_id" => '9',
            "nama" => "MS GLOW MEN Paket Maskulin",
            "slug" => "MS-GLOW-MEN-Paket-Maskulin",
            "small_description" => "MS GLOW MEN Paket Maskulin, FacialWash, Serum, BrightCream",
            "description" => "Energizer Facial Wash Membersihkan pori secara menyeluruh dan mencegah penyebab komedo dan jerawat",
            "original_price" => 350000,
            "selling_price" => 280000,
            "image" => "msglow.jpg",
            "qty" => 45,
            "tax" => 500,
            "status" => 1,
            "trending" => 0,
            "meta_title" => "MS Glow Men Paket Maskulin",
            "meta_keyword" => "Ms Glow, Alat Kecantikan, Kecantikan, Skincare, Facial Wash",
            "meta_description" => "macam-macam kebutuhan perawatan wajah",
            ],
            [
            "cate_id" => '9',
            "nama" => "Whitening Day Cream Ms Glow",
            "slug" => "Whitening-Day-Cream-Ms-Glow",
            "small_description" => "Whitening Day Cream Ms Glow 100g",
            "description" => "Day cream ms glow dengan tekstur foundation super lembut bisa cover noda dan pori muka melindungi kulit dari paparan sinar matahari lansung efek glowing",
            "original_price" => 62000,
            "selling_price" => 55000,
            "image" => "msglow2.jpg",
            "qty" => 49,
            "tax" => 500,
            "status" => 1,
            "trending" => 1,
            "meta_title" => "Whitening Day Cream Ms Glow",
            "meta_keyword" => "Ms Glow, Alat Kecantikan, Kecantikan, Skincare, Facial Wash, Whitening Cream",
            "meta_description" => "macam-macam kebutuhan kecantikan",
            ],

        ];
        foreach ($products as $key => $value) {
            DB::table('products')->insert([
                'cate_id' => $value['cate_id'],
                'nama' => $value['nama'],
                'slug' => $value['slug'],
                'small_description' => $value['small_description'],
                'description' => $value['description'],
                'original_price' => $value['original_price'],
                'selling_price' => $value['selling_price'],
                'image' => $value['image'],
                'qty' => $value['qty'],
                'tax' => $value['tax'],
                'status' => $value['status'],
                'trending' => $value['trending'],
                'meta_title' => $value['meta_title'],
                'meta_description' => $value['meta_description'],
                'meta_keyword' => $value['meta_keyword'],
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ]);
        }
    }
}
